source 'https://rubygems.org'

gem 'pry', '~> 0.10.3'
gem 'pry-byebug'
gem 'awesome_print'
gem 'rerun'
gem 'mondo', '~> 0.4.5'
gem 'activesupport', '~> 5.0'
gem 'thor', '~> 0.19.1'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'thin', '~> 1.6', '>= 1.6.4'
gem 'oauth', '~> 0.5.1'
gem 'http', '~> 0.9.8'
gem 'dotenv'
gem 'omniauth-mondo'
gem 'omniauth'
gem 'rack'
gem 'sprockets'
